name: Documentation Workflow

on:
  push:
    branches:
      - main

jobs:
  change-url:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies 
      run: |
        pip install pdoc3
        npm install -g docusaurus
        npm install

    - name: Build
      run: |
        pdoc --output-dir=website2/docs my_module.py
        npm run build --prefix website2

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "mmt93"
        git config --global user.email "41652032+mmt93@users.noreply.github.com"
        git checkout -b gh-pages
        cp -R build/* .
        git add .
        git commit -m "Deploy Docusaurus to GitHub Pages"
        git push origin gh-pages
