name: Documentation Workflow

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install pdoc3
        npm install -g docusaurus
        npm install
    - name: Build documentation
      run: |
        pdoc --html my_module.py
        npm run build --prefix website2/
    - name: Commit changes
      run: |
        git config --global user.name "mmt93"
        git config --global user.email "41652032+mmt93@users.noreply.github.com"
        git add testpdocusaurus/website2/
        git commit -m "Update documentation"
        git push
